
MODULE_TOPDIR = ../..

PGM = v.rmarea

LIBES = $(VECTORLIB) $(DIG2LIB) $(DBMILIB) $(GISLIB)
DEPENDENCIES = $(VECTORDEP) $(DIG2DEP) $(DBMIDEP) $(GISDEP)
EXTRA_INC = $(VECT_INC)
EXTRA_CFLAGS = $(VECT_CFLAGS)
CLEAN_SUBDIRS = test

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
